swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /id:
    get:
      operationId: engine.generate_id
      tags:
        - ID
      summary: Creates a new id for someone.
      description: Creates a new id for someone and a folder named with the new id.
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: object
            properties:
              id:
                type: string
  
  /upload:
    post:
      tags:
        - Upload
      operationId: engine.upload
      summary: Uploads the contents of a zip file.
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          in: formData
          required: True
          description: ID of user.
          type: string
        - name: upload_file
          in: formData
          type: file
          description: Contents of the ZIP file.
          required: True
      responses:
        201:
          description: Successfully uploaded the file.

